### ISSUE TITLE
Add support for sgrep registry

### ISSUE THREAD

**Issue by dlukeomalley** [returntocorp/bento#312]
**Is your feature request related to a problem? Please describe.**
I'd like the ability to specify multiple local and remote pattern files for my Bento to run. I've found myself wanting to run patterns that don't (yet) ship in `r2c.registry.latest`, some of which are custom to a codebase and some of which are published publicly but too experimental to be added to r2c's "golden registry". 

**Describe the solution you’d like**
I'm not sure exactly how this works with Bento's language and framework discovery. As a v0 I'd be fine manually adding sgrep pattern files to `.bento/config.yml`. I envisioned something like:

```yaml
tool:
    sgrep:
        run: true
        check-packs:
            "r2c.registry.latest": https://urlforconfig.yml
            "my.special.config": https:mydomain.yml
            "r2c.bento-core.custom": local/file/path
        ignores:
            r2c.registry.latest:
                - eq-eq
```

I could imagine simplifying this by having pattern files define their own "tool name".

```yml
tool:
    sgrep:
        run: true
        check-packs:
            - https://urlforconfig.yml
            - local/file/path
            - overrideName: r2c.bento.custom
               url: https://...
        ignores:
            r2c.registry.latest:
                - eq-eq
```

**Comment by dlukeomalley** [comment]
An alternative approach is something along the lines of:

```sh
$ bento enable tool https://sgrep-config-url
```

Each sgrep config URL would be added as it's own tools, with its own ignores.

**Comment by dlukeomalley** [comment]
Alternative proposal:

```yaml
tools:
  sgrep:
    packages:
      - r2c.django
      - r2c.flask
      - url: https://my-custom-sgrep-checks.com
         name: bento.spellcheck
```
