### ISSUE TITLE
Bento did not populate ignore entries

### ISSUE THREAD

**Issue by pabloest** [returntocorp/bento#6]
I installed Bento `0.1.0b2` and configured it in the [Zulip repo](https://github.com/zulip/zulip).

Then I tried to run `bento check` and I saw thousands of “style and formatting” types of warnings and errors.

This is the contents of `.bento.yml`:
```
formatter:
  bento.formatter.Stylish: {}
tools:
  r2c.eslint:
    ignore: []
  r2c.flake8:
    ignore: []
```

Per @minusworld, `ignore` should be populated with entries for ESLint and Flake8.
